services:

  app:
    depends_on:
      - db
    image: app-dev
    build:
      context: .
      dockerfile: app.dockerfile
    networks:
      - app
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /stack-simple/app
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0"]

  db:
    image: postgres:16
    networks:
      - app
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

networks:
  app:
    driver: bridge
